-- AlterTable
ALTER TABLE "users" ADD COLUMN     "role" VARCHAR(30) NOT NULL DEFAULT 'FARM_CLERK',
ADD COLUMN     "status" VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
ADD COLUMN     "token_version" INTEGER NOT NULL DEFAULT 0;
